apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ok-dummy-hpa
  namespace: optikube-dummy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ok-dummy-deploy
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 45
      - type: Percent
        value: 10
        periodSeconds: 45
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      - type: Pods
        value: 5
        periodSeconds: 15
      selectPolicy: Max