apiVersion: apps/v1
kind: Deployment
metadata:
  name: ok-dummy-deploy
  namespace: optikube-dummy
spec:
  selector:
    matchLabels:
      app: optikube-dummy
  template:
    metadata:
      labels:
        app: optikube-dummy
    spec:
      containers:
      - name: ok-dummy
        image: gcr.io/utility-folder-419300/ok-dummy-1.0p
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 700m
          requests:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: ok-dummy-svc
  labels:
    app: opitkube-dummy
spec:
  type: LoadBalancer
  ports:
  - port: 30
    targetPort: 3000
  selector:
    app: optikube-dummy