apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-php-deploy
  namespace: dummy-php
spec:
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: dummy-php
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 700m
          requests:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-php-svc
  labels:
    app: dummy-php
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: php-apache