apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: gcr.io/hardy-nation-412201/mercury-optikube-dummy-app
        ports:
        - containerPort: 3000